site_name: Fylik API Docs
repo_url: https://github.com/hoolie-projects/fylik-web
copyright: "&copy; 2022 Hoolie Projects"

theme:
  name: material
  favicon: 'assets/favicon.ico'
  palette:
    primary: red
  features:
    - navigation.expand

extra:
  generator: false

nav:
  - Home: index.md
  - 'Getting file list': fileList.md
  - 'File upload': upload.md
  - 'Upload limits': limits.md
  - 'File download': download.md
  - Models:
    - 'File model': 'fileModel.md'
